### ISSUE TITLE
Not working with i3

### ISSUE THREAD

**Issue by infokiller** [jakebian/snaptile#16]
I'm able to start `snaptile.py`, but then I get the following error after any keybinding (for example `Ctrl + Alt + e`):

```
<class 'Xlib.protocol.request.QueryExtension'>
Snaptile running. Press CTRL+C to quit.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 682, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "./snaptile.py", line 86, in checkevt
    handleevt(event.detail, event.detail)
  File "./snaptile.py", line 105, in handleevt
    posmap[endkey]
  File "/home/snaptile/window.py", line 4, in position
    window, screen = active_window()
  File "/home/snaptile/window.py", line 31, in active_window
    if no_window(screen, window):
  File "/home/snaptile/window.py", line 45, in no_window
    not screen.supports_net_wm_hint(
AttributeError: 'gtk.gdk.X11Screen' object has no attribute 'supports_net_wm_hint'
```

**Comment by yonseokim** [comment]
Any update on this issue? I'm trying out and getting the same error.
